# Generated by Django 2.0.6 on 2019-07-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=250, null=True)),
                ('address', models.CharField(default='', max_length=250, null=True)),
                ('otp', models.CharField(max_length=200, null=True)),
                ('otp_gen_time', models.CharField(max_length=200, null=True)),
                ('isactive', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=200)),
                ('roleid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.userrole')),
            ],
        ),
    ]
