# Generated by Django 2.0.6 on 2019-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managerrole',
            fields=[
                ('managerid', models.AutoField(primary_key=True, serialize=False)),
                ('managername', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
    ]
